name:       polling-cache
version:    0.0.1.0
github:     "jkaye2012/polling-cache"
license:    BSD3
author:     "Jordan Kaye"
maintainer: "jordan.kaye2@gmail.com"
copyright:  "2021 Jordan Kaye"
category:   Cache,"Distributed Computing"

extra-source-files:
  - README.org
  - ChangeLog.org

description: Please see the project on GitHub at <https://github.com/jkaye2012/polling-cache>

ghc-options:
  - -Wall
  - -Werror
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base
  - exceptions
  - random
  - stm
  - time
  - unliftio

library:
  source-dirs: src

tests:
  polling-cache-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - polling-cache
      - hspec
      - hspec-discover
      - mtl
      - transformers
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
