name: build-and-test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
          stack-setup-ghc: true
      - run: stack build
      - run: stack test
      - run: stack haddock
